updated UI and use Places API
places API servlet, new buttons, new success banner

backend uses proper GET and POST

ajax POST

class-based back end, results page, better form UI

geoLocation

Combine with authentication and datastore feature

Removed ignored files

update query function

Remove Ignored Files

Account header remains

index.yaml file for datastore sorting

Address PR comments

Create .gitignore

Remove ignored files

Fix typo, minor fixes to get deployment working

target files problem

weight in Restaurant.java is now transient, resolve merge conflicts

Removed Ignored Files

Address David PR comments: formatting + small changes

Implement HTTP Session

Make functions serializable

Consistency with list vs arraylist

added tests, minor clean up of Response.java and Restaurant.java

initial geoLoc fallback, function comments/sections in query.js

add ratings and photo to results page

remove Australia as default location text

Fix compilation error: rename photo_reference

In queryservlet change if-if to if-elseif

Tests for QueryServlet

ConvertLocationservlet test and add interface to convertLocationservlet

Beginning of SearchServletTest

Fix typos in servlets : add dependencies for SearchServletTest to work

Add tests to SearchServletTest