Updates to the FavFoodServlet (#39)
* fix merge conflicts

* fix merge conflicts, add changes

* Past searches cards are added, struggling with formatting, variable names are a work in progress

* restaurant name carries through to feedback form

* feedback servlet form submission completed, servlet is fully functional

* UI updates + remove commented out lines, add extra line at end of file

* deleted weird files

* feedback servlet changes imported

* start adding comments, fix merge conflicts

* imported changes from updatedSearches branch, add comments

* fix changes that were not transferred from updatedSearches branch, add more comments

* more changes from updatedSearches moved over

* add space between if and (

* fix order of import statement, extra comment signs, and unnecessary comments

* deleted old files in target, add line

* add spaces, fix function syntax, delete duplicated file

* add user to FavFoodServlet --> user now sees the favorite food they inputted

* resolve PR comments: fix convoluted for loops, update comments

* resolve PR comments, fix issues in favFoodServlet

* updated UI and use Places API

places API servlet, new buttons, new success banner

backend uses proper GET and POST

ajax POST

class-based back end, results page, better form UI

geoLocation

Combine with authentication and datastore feature

Removed ignored files

update query function

Remove Ignored Files

Account header remains

index.yaml file for datastore sorting

Address PR comments

Create .gitignore

Remove ignored files

Fix typo, minor fixes to get deployment working

target files problem

weight in Restaurant.java is now transient, resolve merge conflicts

Removed Ignored Files

Address David PR comments: formatting + small changes

Implement HTTP Session

Make functions serializable

Consistency with list vs arraylist

added tests, minor clean up of Response.java and Restaurant.java

initial geoLoc fallback, function comments/sections in query.js

add ratings and photo to results page

remove Australia as default location text

Fix compilation error: rename photo_reference

In queryservlet change if-if to if-elseif

Tests for QueryServlet

ConvertLocationservlet test and add interface to convertLocationservlet

Beginning of SearchServletTest

Fix typos in servlets : add dependencies for SearchServletTest to work

Add tests to SearchServletTest

* Clean up tests after Rebasing from master

* Add more test for datastore, add test for login

* Address Catherine PR Comments: remove initmocks and change imports

* fix merge conflicts

* fix merge conflicts, add changes

* Past searches cards are added, struggling with formatting, variable names are a work in progress

* restaurant name carries through to feedback form

* feedback servlet form submission completed, servlet is fully functional

* UI updates + remove commented out lines, add extra line at end of file

* deleted weird files

* feedback servlet changes imported

* start adding comments, fix merge conflicts

* imported changes from updatedSearches branch, add comments

* fix changes that were not transferred from updatedSearches branch, add more comments

* more changes from updatedSearches moved over

* UI update

* deleted old files in target, add line

* Move static imports and change to camelCase

* add spaces, fix function syntax, delete duplicated file

* add user to FavFoodServlet --> user now sees the favorite food they inputted

* fix merge conflicts

* restaurant name carries through to feedback form

* feedback servlet form submission completed, servlet is fully functional

* UI updates + remove commented out lines, add extra line at end of file

* deleted weird files

* start adding comments, fix merge conflicts

* imported changes from updatedSearches branch, add comments

* fix changes that were not transferred from updatedSearches branch, add more comments

* more changes from updatedSearches moved over

* removed target and old (unused) files from git

* fix issue from merge, change syntax of async function

* fix function syntax

* all tests pass except one in FavFoodServletTest and one in QueryServleetTest

* errors and failures resolved

* fix PR comments

Co-authored-by: ryan <ryangudal@gmail.com>
Co-authored-by: Jason Han <jjhan@vassar.edu>