Results Page (#19)
* updated UI and use Places API

* places API servlet, new buttons, new success banner

* backend uses proper GET and POST

* ajax POST

* class-based back end, results page, better form UI

* geoLocation

* Combine with authentication and datastore feature

* Removed ignored files

* update query function

* Remove Ignored Files

* Account header remains

* index.yaml file for datastore sorting

* target files problem

* Address PR comments

* Create .gitignore

* Remove ignored files

* Fix typo, minor fixes to get deployment working

* Address David PR Comments

* Fix dependency typo

* remove unnecessary expose annotations and NullPointerException

* weight in Restaurant.java is now transient, resolve merge conflicts

* Fix typos and format in order to deploy

* Removed Ignored Files

* Address David PR comments: formatting + small changes

* Add HTTP session

* Implement HTTP Session

* Make functions serializable

* Consistency with list vs arraylist

* added tests, minor clean up of Response.java and Restaurant.java

* initial geoLoc fallback, function comments/sections in query.js

* proper IP-based geoLoc fallback

* add ratings and photo to results page

* remove Australia as default location text

* Code cleanup: reword comments, change function names, ensure working deployment

* Address David PR Comments

* Fix compilation error: rename photo_reference

* Spacing fix

* Rename Class, make variables more clear

* Fix Typos

* In queryservlet change if-if to if-elseif

* fix capitalization in UserFeedback comment

* Address David PR comments

* Clarifying comment for form.js

* Handle situation where List is empty

* Address David PR comments : add error messages

Co-authored-by: Jason Han <jjhan@vassar.edu>
Co-authored-by: Emma Dunn <evd1@rice.edu>
Co-authored-by: rgudal <rgudal@umich.edu>