updated UI and use Places API
places API servlet, new buttons, new success banner

backend uses proper GET and POST

ajax POST

class-based back end, results page, better form UI

geoLocation

Combine with authentication and datastore feature

Removed ignored files

update query function

Remove Ignored Files

Account header remains

index.yaml file for datastore sorting

Address PR comments

Create .gitignore

Remove ignored files

Fix typo, minor fixes to get deployment working

Fix typos and format in order to deploy

target files problem

weight in Restaurant.java is now transient, resolve merge conflicts

Removed Ignored Files

Address David PR comments: formatting + small changes

Implement HTTP Session

Make functions serializable

Consistency with list vs arraylist

added tests, minor clean up of Response.java and Restaurant.java

initial geoLoc fallback, function comments/sections in query.js

proper IP-based geoLoc fallback

add ratings and photo to results page

remove Australia as default location text

Code cleanup: reword comments, change function names, ensure working deployment

Address David PR Comments

Fix compilation error: rename photo_reference

In queryservlet change if-if to if-elseif

Address David PR comments

Clarifying comment for form.js

Handle situation where List is empty

Create a class that accesses secretmanager

Access Secret Correct implementation + removing embedded API keys

Create a class that accesses secretmanager

Access Secret Correct implementation + removing embedded API keys

Rebase hide-yo-keys and resultsPage

Access Secret Correct implementation + removing embedded API keys

Access Secret Correct implementation + removing embedded API keys

Create .gitignore

Create .gitignore

Remove ignored files

Address David PR Comments

Fix typos and format in order to deploy

weight in Restaurant.java is now transient, resolve merge conflicts

Removed Ignored Files

Address David PR comments: formatting + small changes

Add HTTP session

Implement HTTP Session

Make functions serializable

Consistency with list vs arraylist

added tests, minor clean up of Response.java and Restaurant.java

proper IP-based geoLoc fallback

add ratings and photo to results page

remove Australia as default location text

Address David PR Comments

Fix compilation error: rename photo_reference

In queryservlet change if-if to if-elseif

Address David PR comments

Clarifying comment for form.js

Handle situation where List is empty

Address David PR comments : add error messages

Access Secret Correct implementation + removing embedded API keys

Access Secret Correct implementation + removing embedded API keys

Rebase hide-yo-keys and resultsPage

Access Secret Correct implementation + removing embedded API keys

Create .gitignore

Bug fix to get deployment working

Restaurant Images routed through servlet to protect API key

Move Geolocation to Servlet

Remove debug statements

Address PR comments: make access secret a singleton

IOException caught

Style header in caps